baseurl = "https://asaunders.com/"
theme = "material"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "docs"
author = "Alex Saunders"
title = "Alex Saunders"
disqusshortname = "asaunders"
pluralizelisttitles = false

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Alex Saunders' personal site"
faviconfile = "favicon.ico"
highlightjs = true
lang = "en"
github = "example"
email = "you@example.com"
linkedin = "john-example-aa80ue8è"
twitter = "@example"

[taxonomies]
project-tag = "projectTags"
blog-tag = "blogTags"
