baseurl = "https://alex-saunders.github.io/portfolio"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "docs"
author = "Alex Saunders"
title = "Alex Saunders"
disqusshortname = "asaunders"
pygmentsuseclasses = true
pluralizelisttitles = false

[taxonomies]
tag = "tags"
category = "categories"

[params]
author = "Alex Saunders"
cachebuster = true
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Example blog"
logofile = "img/logo.png"
faviconfile = "img/favicon.ico"
highlightjs = true
lang = "en"
github = "https://github.com/alex-saunders"
linkedin = "https://uk.linkedin.com/in/alexjrsaunders"
twitter = "https://twitter.com/AlexJRsaunders"
